window.QUAGEN_PLAYLIST = [
  { src: "assets/songs/Anthem.mp3", cover: "assets/covers/anthem.jpg" },
  { src: "assets/songs/Capella Grey - _Gyalis_.mp3", cover: "assets/covers/Capella Grey - _Gyalis_.jpg" },
  { src: "assets/songs/FattMack - Lunch Break Freestyle.mp3", cover: "assets/covers/FattMack - Lunch Break Freestyle.jpg" },
  { src: "assets/songs/G Herbo - Went Legit.mp3", cover: "assets/covers/G Herbo - Went Legit.jpg" },
  { src: "assets/songs/Gunna - wgft (feat. Burna Boy).mp3", cover: "assets/covers/Gunna - wgft (feat. Burna Boy).jpg" },
  { src: "assets/songs/Hurricane Wisdom - My Life.mp3", cover: "assets/covers/Hurricane Wisdom - My Life.jpg" },
  { src: "assets/songs/Hurricane Wisdom - Pray.mp3", cover: "assets/covers/Hurricane Wisdom - Pray.jpg" },
  { src: "assets/songs/Hurricane Wisdom - Rich Dropout.mp3", cover: "assets/covers/Hurrciane Wisdom - Rich Dropout.jpg" },
  { src: "assets/songs/Jace! - Do Nun For Ya.mp3", cover: "assets/covers/Jace! - Do Nun For Ya.jpg" },
  { src: "assets/songs/Jace! - Love Ya' More!.mp3", cover: "assets/covers/Jace! - Love Ya'More!.jpg" },
  { src: "assets/songs/Jace! - Still Breathin!.mp3", cover: "assets/covers/Jace! - Still Breathin!.jpg" },
  { src: "assets/songs/Lil Durk - What Happened to Virgil ft. Gunna.mp3", cover: "assets/covers/Lil Durk - What Happen To Virgil ft. Gunna.jpg" },
  { src: "assets/songs/Lil Tony - Watch The Moon.mp3", cover: "assets/covers/Lil Tony - Watch The Moon.jpg" },
  { src: "assets/songs/Lil Uzi Vert - What You Saying.mp3", cover: "assets/covers/Lil Uzi Vert - What You Saying.jpg" },
  { src: "assets/songs/mofe. - Prince Of Egypt.mp3", cover: "assets/covers/mofe. - Prince Of Egypt.jpg" },
  { src: "assets/songs/Nino Paid - Tree On The Hill.mp3", cover: "assets/covers/Nino Paid - Tree On The Hill.jpg" },
  { src: "assets/songs/PlaqueBoyMax x DDG - Pink Dreads.mp3", cover: "assets/covers/PlaqueBoyMax x DDG - Pink Dreads.jpg" },
  { src: "assets/songs/Raq baby - DoorDash (OMG).mp3", cover: "assets/covers/Raq Baby - Doordash (OMG).jpg" },
  { src: "assets/songs/SoFaygo - MM3.mp3", cover: "assets/covers/SoFaygo - MM3.jpg" },
  { src: "assets/songs/Sturdyyoungin, Ohthatsmizz & Zeddy Will - TRIPPIN.mp3", cover: "assets/covers/Sturdyyoungin, Ohthatsmizz & Zeddy Will - TRIPPIN.jpg" },
  { src: "assets/songs/Baby Qato Ft Vonno - Flu Game¿.mp3", cover: "assets/covers/qato.jpg" },
  { src: "assets/songs/BabyChiefDoIt - Ghetto Love Story.mp3", cover: "assets/covers/qato.jpg" },
  { src: "assets/songs/Boobeyy - Party In My House.mp3", cover: "assets/covers/qato.jpg" },
  { src: "assets/songs/Boobeyy Ft SafeHuntin - GLE.mp3", cover: "assets/covers/qato.jpg" },
  { src: "assets/songs/Cheif Dooka Ft Lil Kujo- Ride With Me.mp3", cover: "assets/covers/qato.jpg" },
  { src: "assets/songs/Chief Dooka  -  Disses To Everybody.mp3", cover: "assets/covers/qato.jpg" },
];